export type FileType =
  | "folder"
  | "document"
  | "spreadsheet"
  | "image"
  | "video"
  | "pdf"
  | "code"
  | "archive"
  | "audio"
  | "unknown"

export type SharedRole = "viewer" | "editor"

export type SharedUser = {
  name: string
  avatar?: string
  role: SharedRole
}

export type FileOwner = {
  name: string
  avatar?: string
}

export type FileItem = {
  id: string
  name: string
  type: FileType
  mimeType?: string
  size: number
  path: string[]
  createdAt: string
  modifiedAt: string
  owner: FileOwner
  starred: boolean
  shared: boolean
  sharedWith?: SharedUser[]
  trashed: boolean
  parentId: string | null
}

export type StorageUsage = {
  used: number
  total: number
}

const owner = { name: "Martine Vogel", avatar: "/avatars/martine.jpg" }
const teamMember1 = { name: "Alex Chen", avatar: "/avatars/alex.jpg" }
const teamMember2 = { name: "Jordan Park" }
const teamMember3 = { name: "Sam Rivera", avatar: "/avatars/sam.jpg" }

export const mockFiles: FileItem[] = [
  // root folders
  {
    id: "folder-documents",
    name: "Documents",
    type: "folder",
    size: 0,
    path: [],
    createdAt: "2025-09-15T10:00:00Z",
    modifiedAt: "2026-01-20T14:30:00Z",
    owner,
    starred: true,
    shared: false,
    trashed: false,
    parentId: null,
  },
  {
    id: "folder-images",
    name: "Images",
    type: "folder",
    size: 0,
    path: [],
    createdAt: "2025-10-01T09:00:00Z",
    modifiedAt: "2026-01-18T11:00:00Z",
    owner,
    starred: false,
    shared: true,
    sharedWith: [
      { ...teamMember1, role: "editor" },
      { ...teamMember2, role: "viewer" },
    ],
    trashed: false,
    parentId: null,
  },
  {
    id: "folder-projects",
    name: "Projects",
    type: "folder",
    size: 0,
    path: [],
    createdAt: "2025-08-20T08:00:00Z",
    modifiedAt: "2026-01-22T16:45:00Z",
    owner,
    starred: true,
    shared: true,
    sharedWith: [
      { ...teamMember1, role: "editor" },
      { ...teamMember3, role: "editor" },
    ],
    trashed: false,
    parentId: null,
  },
  {
    id: "folder-archive",
    name: "Archive",
    type: "folder",
    size: 0,
    path: [],
    createdAt: "2025-06-10T12:00:00Z",
    modifiedAt: "2025-12-05T09:30:00Z",
    owner,
    starred: false,
    shared: false,
    trashed: false,
    parentId: null,
  },
  {
    id: "folder-shared-assets",
    name: "Shared Assets",
    type: "folder",
    size: 0,
    path: [],
    createdAt: "2025-11-01T10:00:00Z",
    modifiedAt: "2026-01-15T13:20:00Z",
    owner: teamMember1,
    starred: false,
    shared: true,
    sharedWith: [
      { ...owner, role: "editor" },
      { ...teamMember2, role: "viewer" },
    ],
    trashed: false,
    parentId: null,
  },

  // Documents folder contents
  {
    id: "doc-proposal",
    name: "Project Proposal.docx",
    type: "document",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 245_000,
    path: ["Documents"],
    createdAt: "2025-11-10T14:00:00Z",
    modifiedAt: "2026-01-19T10:15:00Z",
    owner,
    starred: true,
    shared: true,
    sharedWith: [{ ...teamMember1, role: "editor" }],
    trashed: false,
    parentId: "folder-documents",
  },
  {
    id: "doc-meeting-notes",
    name: "Meeting Notes - Jan 2026.docx",
    type: "document",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 128_500,
    path: ["Documents"],
    createdAt: "2026-01-05T09:00:00Z",
    modifiedAt: "2026-01-22T11:30:00Z",
    owner,
    starred: false,
    shared: false,
    trashed: false,
    parentId: "folder-documents",
  },
  {
    id: "doc-budget",
    name: "Budget 2026.xlsx",
    type: "spreadsheet",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    size: 890_000,
    path: ["Documents"],
    createdAt: "2025-12-01T08:00:00Z",
    modifiedAt: "2026-01-21T15:00:00Z",
    owner,
    starred: true,
    shared: true,
    sharedWith: [
      { ...teamMember1, role: "editor" },
      { ...teamMember3, role: "viewer" },
    ],
    trashed: false,
    parentId: "folder-documents",
  },
  {
    id: "doc-contract",
    name: "Vendor Contract.pdf",
    type: "pdf",
    mimeType: "application/pdf",
    size: 1_540_000,
    path: ["Documents"],
    createdAt: "2025-10-20T11:00:00Z",
    modifiedAt: "2025-10-20T11:00:00Z",
    owner,
    starred: false,
    shared: false,
    trashed: false,
    parentId: "folder-documents",
  },
  {
    id: "doc-timeline",
    name: "Project Timeline.xlsx",
    type: "spreadsheet",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    size: 456_000,
    path: ["Documents"],
    createdAt: "2025-11-28T13:00:00Z",
    modifiedAt: "2026-01-18T09:45:00Z",
    owner,
    starred: false,
    shared: true,
    sharedWith: [{ ...teamMember2, role: "viewer" }],
    trashed: false,
    parentId: "folder-documents",
  },
  {
    id: "folder-documents-reports",
    name: "Reports",
    type: "folder",
    size: 0,
    path: ["Documents"],
    createdAt: "2025-10-05T10:00:00Z",
    modifiedAt: "2026-01-15T14:00:00Z",
    owner,
    starred: false,
    shared: false,
    trashed: false,
    parentId: "folder-documents",
  },

  // Documents/Reports subfolder
  {
    id: "doc-q4-report",
    name: "Q4 2025 Report.pdf",
    type: "pdf",
    mimeType: "application/pdf",
    size: 2_100_000,
    path: ["Documents", "Reports"],
    createdAt: "2026-01-02T10:00:00Z",
    modifiedAt: "2026-01-10T16:00:00Z",
    owner,
    starred: false,
    shared: true,
    sharedWith: [
      { ...teamMember1, role: "viewer" },
      { ...teamMember3, role: "viewer" },
    ],
    trashed: false,
    parentId: "folder-documents-reports",
  },
  {
    id: "doc-analytics",
    name: "Site Analytics.xlsx",
    type: "spreadsheet",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    size: 670_000,
    path: ["Documents", "Reports"],
    createdAt: "2025-12-20T14:00:00Z",
    modifiedAt: "2026-01-15T14:00:00Z",
    owner: teamMember1,
    starred: false,
    shared: true,
    sharedWith: [{ ...owner, role: "editor" }],
    trashed: false,
    parentId: "folder-documents-reports",
  },

  // Images folder contents
  {
    id: "img-hero",
    name: "hero-banner.png",
    type: "image",
    mimeType: "image/png",
    size: 3_200_000,
    path: ["Images"],
    createdAt: "2025-12-10T10:00:00Z",
    modifiedAt: "2025-12-10T10:00:00Z",
    owner,
    starred: false,
    shared: true,
    sharedWith: [{ ...teamMember2, role: "viewer" }],
    trashed: false,
    parentId: "folder-images",
  },
  {
    id: "img-logo",
    name: "compass-logo.svg",
    type: "image",
    mimeType: "image/svg+xml",
    size: 12_400,
    path: ["Images"],
    createdAt: "2025-09-01T08:00:00Z",
    modifiedAt: "2025-11-15T16:30:00Z",
    owner,
    starred: true,
    shared: true,
    sharedWith: [
      { ...teamMember1, role: "editor" },
      { ...teamMember2, role: "viewer" },
    ],
    trashed: false,
    parentId: "folder-images",
  },
  {
    id: "img-mockup",
    name: "dashboard-mockup.fig",
    type: "image",
    mimeType: "application/x-figma",
    size: 8_900_000,
    path: ["Images"],
    createdAt: "2025-11-20T14:00:00Z",
    modifiedAt: "2026-01-10T11:00:00Z",
    owner: teamMember1,
    starred: false,
    shared: true,
    sharedWith: [{ ...owner, role: "editor" }],
    trashed: false,
    parentId: "folder-images",
  },
  {
    id: "img-photo1",
    name: "team-photo.jpg",
    type: "image",
    mimeType: "image/jpeg",
    size: 4_500_000,
    path: ["Images"],
    createdAt: "2025-12-20T15:00:00Z",
    modifiedAt: "2025-12-20T15:00:00Z",
    owner: teamMember3,
    starred: false,
    shared: true,
    sharedWith: [
      { ...owner, role: "viewer" },
      { ...teamMember1, role: "viewer" },
    ],
    trashed: false,
    parentId: "folder-images",
  },
  {
    id: "img-screenshot",
    name: "app-screenshot.png",
    type: "image",
    mimeType: "image/png",
    size: 1_800_000,
    path: ["Images"],
    createdAt: "2026-01-08T09:00:00Z",
    modifiedAt: "2026-01-08T09:00:00Z",
    owner,
    starred: false,
    shared: false,
    trashed: false,
    parentId: "folder-images",
  },

  // Projects folder contents
  {
    id: "folder-projects-compass",
    name: "Compass",
    type: "folder",
    size: 0,
    path: ["Projects"],
    createdAt: "2025-08-20T08:00:00Z",
    modifiedAt: "2026-01-22T16:45:00Z",
    owner,
    starred: true,
    shared: true,
    sharedWith: [
      { ...teamMember1, role: "editor" },
      { ...teamMember3, role: "editor" },
    ],
    trashed: false,
    parentId: "folder-projects",
  },
  {
    id: "folder-projects-website",
    name: "Website Redesign",
    type: "folder",
    size: 0,
    path: ["Projects"],
    createdAt: "2025-10-15T09:00:00Z",
    modifiedAt: "2026-01-20T10:00:00Z",
    owner,
    starred: false,
    shared: true,
    sharedWith: [{ ...teamMember1, role: "editor" }],
    trashed: false,
    parentId: "folder-projects",
  },
  {
    id: "proj-spec",
    name: "Technical Spec.md",
    type: "code",
    mimeType: "text/markdown",
    size: 34_000,
    path: ["Projects"],
    createdAt: "2025-09-10T10:00:00Z",
    modifiedAt: "2026-01-15T08:00:00Z",
    owner,
    starred: false,
    shared: true,
    sharedWith: [{ ...teamMember1, role: "editor" }],
    trashed: false,
    parentId: "folder-projects",
  },

  // Projects/Compass subfolder
  {
    id: "compass-readme",
    name: "README.md",
    type: "code",
    mimeType: "text/markdown",
    size: 8_200,
    path: ["Projects", "Compass"],
    createdAt: "2025-08-20T08:30:00Z",
    modifiedAt: "2026-01-22T16:45:00Z",
    owner,
    starred: false,
    shared: true,
    sharedWith: [{ ...teamMember1, role: "editor" }],
    trashed: false,
    parentId: "folder-projects-compass",
  },
  {
    id: "compass-design",
    name: "Design System.fig",
    type: "image",
    mimeType: "application/x-figma",
    size: 15_600_000,
    path: ["Projects", "Compass"],
    createdAt: "2025-09-05T14:00:00Z",
    modifiedAt: "2026-01-18T11:30:00Z",
    owner: teamMember1,
    starred: true,
    shared: true,
    sharedWith: [
      { ...owner, role: "editor" },
      { ...teamMember3, role: "viewer" },
    ],
    trashed: false,
    parentId: "folder-projects-compass",
  },
  {
    id: "compass-api-doc",
    name: "API Documentation.pdf",
    type: "pdf",
    mimeType: "application/pdf",
    size: 980_000,
    path: ["Projects", "Compass"],
    createdAt: "2025-11-01T10:00:00Z",
    modifiedAt: "2026-01-12T14:00:00Z",
    owner,
    starred: false,
    shared: true,
    sharedWith: [{ ...teamMember3, role: "viewer" }],
    trashed: false,
    parentId: "folder-projects-compass",
  },

  // Projects/Website Redesign subfolder
  {
    id: "web-wireframes",
    name: "Wireframes.fig",
    type: "image",
    mimeType: "application/x-figma",
    size: 12_300_000,
    path: ["Projects", "Website Redesign"],
    createdAt: "2025-10-20T11:00:00Z",
    modifiedAt: "2026-01-20T10:00:00Z",
    owner: teamMember1,
    starred: false,
    shared: true,
    sharedWith: [{ ...owner, role: "editor" }],
    trashed: false,
    parentId: "folder-projects-website",
  },
  {
    id: "web-copy",
    name: "Website Copy.docx",
    type: "document",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 67_000,
    path: ["Projects", "Website Redesign"],
    createdAt: "2025-11-15T09:00:00Z",
    modifiedAt: "2026-01-16T13:00:00Z",
    owner,
    starred: false,
    shared: true,
    sharedWith: [{ ...teamMember1, role: "editor" }],
    trashed: false,
    parentId: "folder-projects-website",
  },

  // Shared Assets folder (owned by team member)
  {
    id: "shared-brand-guide",
    name: "Brand Guidelines.pdf",
    type: "pdf",
    mimeType: "application/pdf",
    size: 5_400_000,
    path: ["Shared Assets"],
    createdAt: "2025-11-01T10:00:00Z",
    modifiedAt: "2025-11-01T10:00:00Z",
    owner: teamMember1,
    starred: false,
    shared: true,
    sharedWith: [
      { ...owner, role: "editor" },
      { ...teamMember2, role: "viewer" },
    ],
    trashed: false,
    parentId: "folder-shared-assets",
  },
  {
    id: "shared-icons",
    name: "Icon Set.zip",
    type: "archive",
    mimeType: "application/zip",
    size: 2_300_000,
    path: ["Shared Assets"],
    createdAt: "2025-11-05T14:00:00Z",
    modifiedAt: "2025-11-05T14:00:00Z",
    owner: teamMember1,
    starred: false,
    shared: true,
    sharedWith: [{ ...owner, role: "viewer" }],
    trashed: false,
    parentId: "folder-shared-assets",
  },
  {
    id: "shared-fonts",
    name: "Custom Fonts.zip",
    type: "archive",
    mimeType: "application/zip",
    size: 1_100_000,
    path: ["Shared Assets"],
    createdAt: "2025-11-10T09:00:00Z",
    modifiedAt: "2025-11-10T09:00:00Z",
    owner: teamMember1,
    starred: false,
    shared: true,
    sharedWith: [{ ...owner, role: "editor" }],
    trashed: false,
    parentId: "folder-shared-assets",
  },

  // Root-level files
  {
    id: "root-video",
    name: "Product Demo.mp4",
    type: "video",
    mimeType: "video/mp4",
    size: 45_000_000,
    path: [],
    createdAt: "2025-12-15T16:00:00Z",
    modifiedAt: "2025-12-15T16:00:00Z",
    owner,
    starred: false,
    shared: true,
    sharedWith: [
      { ...teamMember1, role: "viewer" },
      { ...teamMember2, role: "viewer" },
      { ...teamMember3, role: "viewer" },
    ],
    trashed: false,
    parentId: null,
  },
  {
    id: "root-audio",
    name: "Podcast Recording.mp3",
    type: "audio",
    mimeType: "audio/mpeg",
    size: 18_500_000,
    path: [],
    createdAt: "2026-01-05T11:00:00Z",
    modifiedAt: "2026-01-05T11:00:00Z",
    owner: teamMember3,
    starred: false,
    shared: true,
    sharedWith: [{ ...owner, role: "viewer" }],
    trashed: false,
    parentId: null,
  },
  {
    id: "root-presentation",
    name: "Q1 Kickoff.pptx",
    type: "document",
    mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    size: 6_700_000,
    path: [],
    createdAt: "2026-01-02T08:00:00Z",
    modifiedAt: "2026-01-20T17:00:00Z",
    owner,
    starred: true,
    shared: true,
    sharedWith: [
      { ...teamMember1, role: "editor" },
      { ...teamMember3, role: "editor" },
    ],
    trashed: false,
    parentId: null,
  },
  {
    id: "root-config",
    name: "deploy-config.yaml",
    type: "code",
    mimeType: "text/yaml",
    size: 2_400,
    path: [],
    createdAt: "2025-11-20T10:00:00Z",
    modifiedAt: "2026-01-10T09:00:00Z",
    owner,
    starred: false,
    shared: false,
    trashed: false,
    parentId: null,
  },

  // Trashed files
  {
    id: "trash-old-draft",
    name: "Old Draft.docx",
    type: "document",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 156_000,
    path: ["Documents"],
    createdAt: "2025-08-10T10:00:00Z",
    modifiedAt: "2025-12-28T14:00:00Z",
    owner,
    starred: false,
    shared: false,
    trashed: true,
    parentId: "folder-documents",
  },
  {
    id: "trash-screenshot",
    name: "old-screenshot.png",
    type: "image",
    mimeType: "image/png",
    size: 2_400_000,
    path: ["Images"],
    createdAt: "2025-07-15T09:00:00Z",
    modifiedAt: "2025-12-20T11:00:00Z",
    owner,
    starred: false,
    shared: false,
    trashed: true,
    parentId: "folder-images",
  },
  {
    id: "trash-backup",
    name: "backup-nov.zip",
    type: "archive",
    mimeType: "application/zip",
    size: 34_000_000,
    path: [],
    createdAt: "2025-11-30T22:00:00Z",
    modifiedAt: "2026-01-05T08:00:00Z",
    owner,
    starred: false,
    shared: false,
    trashed: true,
    parentId: null,
  },

  // Archive folder contents
  {
    id: "archive-old-project",
    name: "2024 Campaign.zip",
    type: "archive",
    mimeType: "application/zip",
    size: 89_000_000,
    path: ["Archive"],
    createdAt: "2025-01-15T10:00:00Z",
    modifiedAt: "2025-06-10T12:00:00Z",
    owner,
    starred: false,
    shared: false,
    trashed: false,
    parentId: "folder-archive",
  },
  {
    id: "archive-legacy-docs",
    name: "Legacy Documentation.pdf",
    type: "pdf",
    mimeType: "application/pdf",
    size: 3_200_000,
    path: ["Archive"],
    createdAt: "2025-03-20T14:00:00Z",
    modifiedAt: "2025-03-20T14:00:00Z",
    owner,
    starred: false,
    shared: false,
    trashed: false,
    parentId: "folder-archive",
  },
  {
    id: "archive-old-video",
    name: "Training Video 2024.mp4",
    type: "video",
    mimeType: "video/mp4",
    size: 120_000_000,
    path: ["Archive"],
    createdAt: "2024-11-10T16:00:00Z",
    modifiedAt: "2024-11-10T16:00:00Z",
    owner,
    starred: false,
    shared: false,
    trashed: false,
    parentId: "folder-archive",
  },
]

export const mockStorageUsage: StorageUsage = {
  used: 412_000_000,
  total: 5_000_000_000,
}
