"use client"

import { XIcon, Loader2Icon } from "lucide-react"
import { Button } from "@/components/ui/button"
import { useRenderState } from "./chat-provider"
import { CompassRenderer } from "@/lib/agent/render/compass-renderer"

export function RenderedView() {
  const {
    spec,
    isRendering,
    error,
    dataContext,
    clearRender,
  } = useRenderState()

  const hasRoot = !!spec?.root

  return (
    <div className="flex flex-1 flex-col min-h-0 p-4">
      {/* Header bar */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          {isRendering && (
            <>
              <Loader2Icon className="size-4 animate-spin" />
              <span>Building interface...</span>
            </>
          )}
          {!isRendering && hasRoot && (
            <span>Generated by Slab</span>
          )}
        </div>
        <Button
          variant="ghost"
          size="sm"
          onClick={clearRender}
          className="gap-1.5"
        >
          <XIcon className="size-4" />
          Clear
        </Button>
      </div>

      {/* Rendered content */}
      <div className="flex-1 overflow-auto">
        <div className="mx-auto max-w-6xl">
          {error && (
            <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-4 text-sm text-destructive">
              Failed to generate UI: {error.message}
            </div>
          )}

          {!hasRoot && isRendering && (
            <div className="flex items-center justify-center py-12">
              <div className="flex flex-col items-center gap-3 text-muted-foreground">
                <Loader2Icon className="size-8 animate-spin" />
                <span className="text-sm">
                  Generating dashboard...
                </span>
              </div>
            </div>
          )}

          {hasRoot && (
            <CompassRenderer
              spec={spec}
              data={dataContext}
              loading={isRendering}
            />
          )}
        </div>
      </div>
    </div>
  )
}
